name: simrun-stratus-adapter
lang: go
lang_version: "1.25.12"
git:
  enable: true
codeowners:
  enable: true
renovatebot:
  enable: true
  automerge:
    enable: true
semaphore:
  enable: true
  pipeline_enable: false
